package cn.edu.bjtu.foodie.bean;

import java.util.Date;

public class Appointment {
	/** primary key generated by guid **/
	private String id;
	/** primary key of the foodie who raise the date **/
	private String foodieId;
	/** date title **/
	private String title;
	/** date description **/
	private String des;
	/** primary key of the restaurant where they have a date **/
	private int restId;
	/** when date begin **/
	private Date time;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getFoodieId() {
		return foodieId;
	}
	public void setFoodieId(String foodieId) {
		this.foodieId = foodieId;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public int getRestId() {
		return restId;
	}
	public void setRestId(int restId) {
		this.restId = restId;
	}
	public Date getTime() {
		return time;
	}
	public void setTime(Date time) {
		this.time = time;
	}
	public String getDes() {
		return des;
	}
	public void setDes(String des) {
		this.des = des;
	}
	
	@Override
	public String toString() {
		return "Appointment [id=" + id + ", foodieId=" + foodieId + ", title="
				+ title + ", des=" + des + ", restId=" + restId + ", time="
				+ time + "]";
	}
	
}
