package cn.edu.bjtu.foodie.bean;

public class Book {
	/** primary key generated by guid **/
	private String id;
	/** primary key of the foodie who submit the book **/
	private String foodieId;
	/** primary key of the restaurant where they have a meal **/
	private String restId;
	/** when meal begin **/
	private java.util.Date time;
	/** 0: not need queue, > 0: queue number(increment) **/
	private int queueNumber;
	/** 0: not confirm, 1: have confirmed **/
	private int status;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getFoodieId() {
		return foodieId;
	}
	public void setFoodieId(String foodieId) {
		this.foodieId = foodieId;
	}
	public String getRestId() {
		return restId;
	}
	public void setRestId(String restId) {
		this.restId = restId;
	}
	public java.util.Date getTime() {
		return time;
	}
	public void setTime(java.util.Date time) {
		this.time = time;
	}
	public int getQueueNumber() {
		return queueNumber;
	}
	public void setQueueNumber(int queueNumber) {
		this.queueNumber = queueNumber;
	}
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	
	@Override
	public String toString() {
		return "Book [id=" + id + ", foodieId=" + foodieId + ", restId="
				+ restId + ", time=" + time + ", queueNumber=" + queueNumber
				+ ", status=" + status + "]";
	}
}
