package cn.edu.bjtu.foodie.bean;

public class Category {
	/** primary key generated by guid **/
	private String id;
	/** category name **/
	private String name;
	/** primary key of the restaurant who manage the category **/
	private int restId;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getRestId() {
		return restId;
	}
	public void setRestId(int restId) {
		this.restId = restId;
	}
	
	@Override
	public String toString() {
		return "Category [id=" + id + ", name=" + name + ", restId=" + restId
				+ "]";
	}
	
}
