package cn.edu.bjtu.foodie.bean;

public class Date {
	/** primary key generated by guid **/
	private String id;
	/** primary key of the foodie who raise the date **/
	private String foodieId;
	/** date title **/
	private String title;
	/** date description **/
	private String desc;
	/** primary key of the restaurant where they have a date **/
	private int restId;
	/** when date begin **/
	private Date time;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getFoodieId() {
		return foodieId;
	}
	public void setFoodieId(String foodieId) {
		this.foodieId = foodieId;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getDesc() {
		return desc;
	}
	public void setDesc(String desc) {
		this.desc = desc;
	}
	public int getRestId() {
		return restId;
	}
	public void setRestId(int restId) {
		this.restId = restId;
	}
	public Date getTime() {
		return time;
	}
	public void setTime(Date time) {
		this.time = time;
	}
	
	@Override
	public String toString() {
		return "Date [id=" + id + ", foodieId=" + foodieId + ", title=" + title
				+ ", desc=" + desc + ", restId=" + restId + ", time=" + time
				+ "]";
	}
	
}
