package cn.edu.bjtu.foodie.bean;

public class Dish {
	/** primary key generated by guid **/
	private String id;
	/** name of the dish **/
	private String name;
	/** price of the dish **/
	private int price;
	/** primary key of the restaurant sell the dish **/
	private int restId;
	/** primary key of the dish category **/
	private int categoryId;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getPrice() {
		return price;
	}
	public void setPrice(int price) {
		this.price = price;
	}
	public int getRestId() {
		return restId;
	}
	public void setRestId(int restId) {
		this.restId = restId;
	}
	public int getCategoryId() {
		return categoryId;
	}
	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}
	
	@Override
	public String toString() {
		return "Dish [id=" + id + ", name=" + name + ", price=" + price
				+ ", restId=" + restId + ", categoryId=" + categoryId + "]";
	}
	
}
