package cn.edu.bjtu.foodie.bean;

public class Friend {
	/** primary key generated by guid **/
	private String id;
	/** foodie's primary key **/
	private String foodieId;
	/** friend's primary key **/
	private String friendId;
	/** status code: -1 for have not agreed by friend, 0 for have agreed by friend**/
	private int status;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getFoodieId() {
		return foodieId;
	}
	public void setFoodieId(String foodieId) {
		this.foodieId = foodieId;
	}
	public String getFriendId() {
		return friendId;
	}
	public void setFriendId(String friendId) {
		this.friendId = friendId;
	}
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	
	@Override
	public String toString() {
		return "Friend [id=" + id + ", foodieId=" + foodieId + ", friendId="
				+ friendId + ", status=" + status + "]";
	}

}
