package cn.edu.bjtu.foodie.bean;

public class Restaurant {
	/** primary key generated by guid **/
	private String id;
	/** restaurantname **/
	private String name;
	/** description **/
	private String description;
	/**  location  **/
	private float longitude;
	private float latitude;
	/**   picture  **/
	private String picture;
	

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

    public float getLongitude(){
    	return longitude;
    }
    public void setLongitude(float longitude){
    	this.longitude = longitude;
    }
    public float getLatitude(){
    	return latitude;
    }
    public void setLatitude(float latitude){
    	this.latitude = latitude;
    }
    public String getPicture(){
    	return picture;
    }
    public void setPicture(String picture){
    	this.picture = picture;
    }

}
